# fly.toml app configuration file generated for discord-exchange-bot on 2025-06-24T14:43:25-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# fly.toml – discord-exchange-bot
# generated 2025-06-24T14:43:25-04:00
# https://fly.io/docs/reference/configuration/

app = "discord-exchange-bot"
primary_region = "ams"

[build]
builder = "paketobuildpacks/builder:base"


[[vm]]
  memory   = "1gb"
  cpu_kind = "shared"
  cpus     = 1

[scale]
  min_machines = 1
  max_machines = 1

[[services]]
  internal_port       = 8080
  protocol            = "tcp"
  auto_stop_machines  = "stop"
  auto_start_machines = true
  # ensure at least one always running
  min_machines_running = 1

  # expose both HTTP (80) and HTTPS (443)
  [[services.ports]]
    port     = 80
    handlers = ["http"]

  [[services.ports]]
    port     = 443
    handlers = ["tls", "http"]

  # health-check: GET /health every 30s, 2s timeout
  [services.http_checks]
    protocol     = "http"
    path         = "/health"
    method       = "GET"
    interval     = 30000   # in ms
    timeout      = 2000    # in ms
    grace_period = "5s"